### ISSUE TITLE
Freya + WebSharper

### ISSUE THREAD

**Issue by panesofglass** [xyncro/freya#107]
Would it be possible to leverage all or parts of WebSharper from Freya?
- [ ] Leverage WebSharper's HTML / JS generation from Freya?
- [ ] UI.Next from Freya?
- [ ] How might we map to RPC methods?
- [ ] How might we map Sitelets?

**Comment by Kavignon** [comment]
Hey, love to know what are the update concerning this question  ?

**Comment by kolektiv** [comment]
Hi @Kavignon - sorry I've been a bit slow replying to this, away over the long weekend, etc. At the moment we've not followed any paths towards WebSharper integration, although both Suave and WebSharper now have OWIN support in some forms so that might well be the most obvious first step to investigate. This is probably a fairly speculative question for now, to be entirely honest!
