### ISSUE TITLE
Spaces in URL are not compatible with UriTemplate's

### ISSUE THREAD

**Issue by mvkra** [xyncro/freya#134]
I've defined a routing template as thus:

let serviceRoutes =
        freyaRouter {
            route (Methods [ GET; ]) (UriTemplate.Parse "/helloworld/{requestId}/{message}") helloWorldHandler
        } 
        |> FreyaRouter.toPipeline

If I type "/helloworld/1/Hello World!" which converts to "Hello%20World!" by my browser I can see that the path is correct (have a logging "freya" block before my routes) but the route never gets hit.

If on the other hand I trye "/helloworld/1/HelloWorld" without spaces on the last part of the URL the route does get hit. Problem is that I want my resources have spaces for names for good or for worse.

Doing this before the request hits the "serviceRoutes" computation expression seems to workaround the issue; 
do! Freya.setLens Request.Path_ (path.Replace(" ", "%20"))
Then when the request is passed to the routes defined above it's in the correct format to parse.

Not sure if this is a bug with Freya or Arachne. It could be that I'm not defining my UriTemplate correctly or Freya is stripping out the "%20" from the Request.Path_ too early.

**Comment by kolektiv** [comment]
Ah, hmmm. Yes that might well be an interesting interaction, my hunch is leaning toward your last sentence. I'll take a look at it as soon as I can.

**Comment by kolektiv** [comment]
Hi @mvkra - sorry not to get back to you sooner than this. Your hunch about percent encoding turned out to be useful, and prompted some changes inside Arachne. However, they turned out not to be the problem (they're just good changes!)

As it turns out, the URI Template standard has different patterns for expanding (and by implication matching) variables in a template. The '!' char is actually a reserved character, and is only part of a variable if it's a reserved variable, not a simple variable. So the expansion (and matching) if you're expecting values with reserved chars in them like '!' should be a reserved variable. So `{+message}` rather than `{message}`.

I can see that we're going to need to write good documents on this, as the fact that it didn't spring to my mind either clearly means that it's not the most obvious thing. Hopefully you're still interested in the answer, and thank you for prompting some interesting changes, and giving me some more docs to write... :+1:

**Comment by mvkra** [comment]
No problem - thanks for getting back to me. Just to clarify I did try {+message} if I recall ages ago and it didn't work either. Would give that a test run to see if it matches the spaces before closing the issue.

As an aside w.r.t documentation more of it is definitely needed; I do understand that this is a new framework however. The more the documentation available that reflects common REST app cases I think the easier the adoption of this library would be.

**Comment by kolektiv** [comment]
Ah ok - well, I tried it just now and it seems to work for me now, so it may be a combination of Arachne and Freya changes. When we get the 3.0 (or even just the next pre-release of Freya 3.0) out, I'd love to see if it's working for you, if you've got time to check.

And yes, you're completely right on the documentation, especially of a cookbook style. It's hard to write, but it really needs doing. If you ever finding yourself thinking "this bit here would be good as a doc" please feel free to raise an issue, I'd love to know about that kind of thing.

**Comment by kolektiv** [comment]
I want to make sure that the 3.0 final release of Arachne and changes to Freya fix this for 3.0.

**Comment by kolektiv** [comment]
I think this was also relating to a recent fix (#174) that went in around OWIN uri-decoding the path, so I am hopeful that this is good now...

**Comment by mexx** [comment]
Looks as the same cause to me. Should be fixed now.
