### ISSUE TITLE
Break up HTTP graph into smaller RFC components

### ISSUE THREAD

**Issue by panesofglass** [xyncro/freya#87]
Breaking up the HTTP graph would allow for finer control over which pieces of the graph are wanted by a given team. @darrelmiller asked me about this at [.NET Fringe](http://dotnetfringe.org/). His concern was executing the entire graph for an app that wouldn't support or ever need to leverage certain pieces of the graph. @darrelmiller, would you mind adding any more specifics in the comments?

**Comment by kolektiv** [comment]
This is definitely interesting, and I'm certainly interested in whether we could do this. It may need a restructure of the graph to make it "thematically" decomposable to some degree, but it's worth a thought experiment at minimum. @darrelmiller - definitely interested in your thoughts.

**Comment by darrelmiller** [comment]
I'll explain my thought process that led to my comments and I'll leave it to you folks to determine the validity of my concerns :-).  
In Ryan's demo he mentioned the notion of having debugging tooling to help pinpoint issues that might occur in the "web machine" whilst processing a request.  I tend to view the need for additional tooling as a smell that might indicate unnecessary complexity.
My question to Ryan was whether it was possible to configure a subset of the "web machine" for a particular resource to reduce the processing complexity and therefore make debugging inherently simpler for that resource.
Upon further reflection, I'm not sure permanently removing pieces of the "web machine" make sense.  It is called a uniform interface for a reason!  Which leads me to my last thought and that is whether it would be possible to remove/disable pieces of the "web machine" temporarily in order to identify the source of a particular problem.  My gut tells me that I'd rather debug a partially disabled "web machine" than to attach a debugging tool to a fully operational, but only partially used "web machine".
However, to borrow the phrase, this is very much just a thought experiment on my part.

**Comment by kolektiv** [comment]
Interesting thoughts! I think I get where you're coming from. In terms of planned tooling, it's essentially a graph based tracing tool, which is essentially to help you work out what actually happened if the result isn't what you expected (which is, hopefully, a rare occurrence) - and also perhaps to help explore functionality (i.e. "ah, if I implemented that decision/config, I could support ETags" or similar).

As you say, permanently removing parts of the graph may lead to unwanted surprises (maybe more within teams, perhaps), but the same mechanism could be used to quite easily to do so either permanently or temporarily (parameterising the function to include a specific graph in a machine execution perhaps).

Definitely something worth thinking about for us, I might try a slightly experimental version of this with a version of the HTTP graph.

Also interested in any other ideas/thoughts you've got in general!
